# ============================================================
# zensical.toml (Zensical configuration file)
# ============================================================

[project]
site_name = "Web Mining and Applied NLP"
site_url = "https://sabrouch36.github.io/nlp-06-nlp-pipeline/"
repo_url = "https://github.com/sabrouch36/nlp-06-nlp-pipeline"
repo_name = "sabrouch36/nlp-06-nlp-pipeline"
site_description = "Web Mining and Applied NLP project documentation"
docs_dir = "docs"
site_dir = "site"
edit_uri = "edit/main/docs/"

[project.extra]
social = [
    {icon = "fontawesome/brands/github", link = "https://github.com/sabrouch36/nlp-06-nlp-pipeline" },
]

# ------------------------------------------------------------
# Plugins
# ------------------------------------------------------------
[project.plugins.search]
lang = "en"

[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
show_source = true
show_root_heading = true
show_root_toc_entry = true
show_signature_annotations = true
separate_signature = true

[project.theme]
features = [
    "navigation.tracking",
    "navigation.expand",
    "navigation.path",
    "navigation.prune",
    "navigation.indexes",
    "toc.follow",
    "toc.integrate",
    "navigation.top",
]

# ------------------------------------------------------------
# Navigation
# ------------------------------------------------------------
nav = [
    { "Home" = "index.md" },
    { "NLP Evolution" = "nlp-evolution.md" },
    { "Glossary" = "glossary.md" },
    { "Project Instructions" = "project-instructions.md" },
]
